remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

title: Robert T. Young, PhD

description: This is the professional website and portfolio page for Robert T. Young, PhD.

author: Robert T Young

avatar: ../external_docs/photos/RY_CareerFair2025_hs01_v02.jpg
